[source]
repository = "git@github.com:ordeal97/ulvz_specfem.git"
commit = "72f0c39117df9395c12fa901a9ae99fa3e7bdfd9"

[environment]
modules = ["gcc/12.4.0", "openmpi/4.1.5"]
mpi_launcher = "mpirun --map-by ppr:64:node --bind-to core --mca pml ucx --mca btl ^openib"

[build]
mesher_target = "meshfem3D"
solver_target = "specfem3D"
