[source]
repository = "git@github.com:ordeal97/ulvz_specfem.git"
commit = "72f0c39117df9395c12fa901a9ae99fa3e7bdfd9"

[environment]
python_bin = "/share/home/yiy/.conda/envs/ulvz-specfem/bin/python3"
oneapi_setup = "/share/apps/intel/oneapi_2023.1.0/setvars.sh"
modules = ["hdf5/1.14.3_oneapi2023"]
mpi_launcher = "mpirun"

[build]
mesher_target = "meshfem3D"
solver_target = "specfem3D"
