#!/usr/bin/env python3
"""Generate the public machine-readable summary from frozen package artifacts."""
from __future__ import annotations
import json,tomllib
from collections import Counter
from production_common import ROOT,rows
from preflight import run_preflight

def main():
 cfg=tomllib.loads((ROOT/'config/production.toml').read_text());contract=tomllib.loads((ROOT/'config/contracts/prem_three_sector.toml').read_text());manifest=rows(ROOT/'production_run_manifest.csv');sources=rows(ROOT/'catalogs/source_ensemble.csv');stations=rows(ROOT/'catalogs/station_geometry.csv');params=rows(ROOT/'catalogs/ulvz_parameter_catalog.csv');summary,_=run_preflight(False)
 mock=json.loads((ROOT/'preflight/mock_submission.json').read_text()) if (ROOT/'preflight/mock_submission.json').is_file() else {'status':'NOT_RUN'}
 output={'package_schema_version':'1.2','n_sources':len(sources),'n_stations':len(stations),'n_station_sectors':len(set(x['sector'] for x in stations)),'n_runs':len(manifest),'n_baseline_runs':sum(x['run_kind']=='baseline' for x in manifest),'n_multi_runs':sum(x['run_kind']=='tri_ulvz' for x in manifest),'n_ulvz_instances':len(params),'nchunks':contract['inputs']['nchunks'],'mpi_ranks':cfg['lsf']['mpi_ranks'],'ptile':cfg['lsf']['ptile'],'max_active_runs':cfg['lsf']['max_active_runs'],'record_length_min':contract['inputs']['record_length_minutes'],'dt_s':contract['inputs']['dt_s'],'nstep':contract['inputs']['expected_nstep'],'expected_npts':contract['inputs']['expected_npts'],'source_depth_quota':dict(Counter(x['depth_bin'] for x in sources)),'mechanism_counts':dict(Counter(x['mechanism_class'] for x in sources)),'parameter_source_counts':dict(Counter(x['parameter_source'] for x in params)),'n_ulvz_baseline':0,'n_ulvz_multi':3,'zero_taper':all(float(x['lateral_taper_km'])==0 and float(x['top_taper_km'])==0 for x in params),'physics_settings':contract['physics'],'whale_runtime':{'python_bin':cfg['runtime']['python_bin'],**cfg['environment']},'stage_barrier':'all stage1_baseline runs must be DONE with output_qc PASS before stage2_multi is eligible','preflight_status':summary['status'],'validate_status':summary['status'],'dry_run_status':summary['status'],'mock_submission_status':mock['status'],'specfem_source_repository':cfg['source']['repository'],'specfem_source_commit':cfg['source']['commit'],'key_paths':{'manifest':'production_run_manifest.csv','source_catalog':'catalogs/source_ensemble.csv','station_catalog':'catalogs/station_geometry.csv','parameter_catalog':'catalogs/ulvz_parameter_catalog.csv','instance_manifest':'catalogs/ulvz_instance_manifest.csv','preflight_report':'preflight/PREFLIGHT_REPORT.md','all_runs_audit':'preflight/all_runs_parameter_audit.csv','template':'specfem_template'},'deployment_time_validation':['Whale Python/numpy/h5py and oneAPI/HDF5/MPI availability','pinned source build and executable link audit','LSF queue, 384-rank host layout, memory and storage','scratch and shared filesystem access','actual mesher/solver/output-QC behavior']}
 (ROOT/'design_summary.json').write_text(json.dumps(output,indent=2,sort_keys=True)+'\n')
if __name__=='__main__':main()
